# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

COPY . .

# Run the main script on container startup
CMD ["python", "main.py"]

EXPOSE 5000